### ISSUE TITLE
Playlist port failing in most recent releases

### ISSUE THREAD

**Issue by dkisselev** [rckclmbr/pyportify#78]
I'm trying to work with the 0.3.6 release but have been running into a bug with fetch_playlist that causes the script to fail.

Here's a stacktrace from Python 3.4 on Ubuntu, but I've also tried on 3.5 with the same result:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyportify-copyall", line 9, in <module>
    load_entry_point('pyportify==0.3.6', 'console_scripts', 'pyportify-copyall')()
  File "/usr/local/lib/python3.4/dist-packages/pyportify/copy_all.py", line 61, in main
    loop.run_until_complete(start())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 236, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.4/dist-packages/pyportify/copy_all.py", line 55, in start
    yield from app.transfer_playlists(None, s, g, playlists)
  File "/usr/local/lib/python3.4/dist-packages/pyportify/app.py", line 133, in transfer_playlists
    sp_playlist = yield from s.fetch_playlist(sp_playlist_uri)
  File "/usr/local/lib/python3.4/dist-packages/pyportify/spotify.py", line 99, in fetch_playlist
    parts = uri.split(':')  # spotify:user:<user_id>:playlist:<playlist_id>
AttributeError: 'dict' object has no attribute 'split'
```

**Comment by programmerpro19** [comment]
Yes, same here.
``
Failed to execute script copy_all
Traceback (most recent call last):
  File "pyportify/copy_all.py", line 66, in <module>
  File "pyportify/copy_all.py", line 61, in main
  File "asyncio/base_events.py", line 387, in run_until_complete
  File "asyncio/futures.py", line 274, in result
  File "asyncio/tasks.py", line 239, in _step
  File "pyportify/copy_all.py", line 55, in start
  File "pyportify/app.py", line 133, in transfer_playlists
  File "pyportify/spotify.py", line 99, in fetch_playlist
AttributeError: 'dict' object has no attribute 'split'
``

**Comment by rckclmbr** [comment]
This is fixed in v0.3.7.  I updated pypi (so you can update to the latest version with pip).  I will update the binaries soon.

**Comment by rckclmbr** [comment]
Download updated
